s3:
  buckets: 
    inputs: ''
    inputs_dest: ''
    data: ''
    data_dest: ''
    results: ''
    results_dest: ''
  aws_secret_access_key: ''
  aws_access_key_id: ''
  region: ''
  cloud_service_provider: 'aws'