s3:
  buckets: 
    inputs: ''
    inputs_dest: ''
    data: ''
    data_dest: ''
    results: ''
    reports: ''
  aws_secret_access_key: ''
  aws_access_key_id: ''
  endpoint_url: ''
  region: ''
  cloud_service_provider: 'ibm'